name: Design Consults Deploy

on:
  push:
    branches:
      - main
    paths:
      - './design-consults/**'
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    # Allow this job to push changes to your repository
    permissions:
      contents: write

    steps:
      - name: Check out your repository using git
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./design-consults
        run: npm ci

      - name: Build Astro
        working-directory: ./design-consults
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./design-consults/dist
